version: "3.7"
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - vnet
  testeappdocker:
    build: ./TesteAppDocker
    ports:
      - "32785:80"
      - "32786:443"
    networks:
      - vnet
  vuejs:
    build: ./vue-project
    ports:
      - "8080:80"
    networks:
      - vnet
networks:
  vnet:
    driver: bridge